name: Integration Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch: # Allow manual triggering

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run all validations
        run: |
          echo "=== Running Schema Validation ==="
          npm run validate-schemas
          
          echo "=== Running Sample Validation ==="
          npm run validate-samples
          
          echo "=== Running Markdown Lint ==="
          npm run lint:markdown
          
          echo "=== Running Format Check ==="
          npm run format:check
          
          echo "=== All validations completed successfully ==="

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: integration-test-results-${{ matrix.node-version }}
          path: |
            test-results/
            *.log
          retention-days: 14

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            let comment = '## Integration Test Results ✅\n\n';
            comment += 'All validation checks passed successfully!\n\n';
            comment += '- ✅ Schema validation\n';
            comment += '- ✅ Sample file validation\n';
            comment += '- ✅ Markdown linting\n';
            comment += '- ✅ Code formatting\n\n';
            comment += 'This PR is ready for review.';
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            }); 